### ISSUE TITLE
Cannot install on Ubuntu Server 14.04 on Node v4.1.1

### ISSUE THREAD

**Issue by seitbekir** [eleith/emailjs#155]
After install I've checked how it works using code:
```
var email   = require("emailjs");
```
also tried:
```
var email   = require("emailjs/email");
```
But got an error:
```
module.js:338
    throw err;
    ^

Error: Cannot find module 'starttls'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/emailjs/smtp/smtp.js:10:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

I've investigate the problem and found that npm not install some modules.
The main problem is that iconv don't want to be installed on Node 4.1.1.

Maybe it's mistake, but this problem not only for me. Please, check it.

I've reprodused this issue on c9.io server instance, so, just try.

**Comment by eleith** [comment]
i can not reproduce. however, i tested with node 4.2.6 instead.

if it can't find starttls, it seems as if a dependency was not installed, but that should be up to the job of the package manager (npm).

starttls is declared appropriately in the package.json so maybe it is a bug with an older version of npm?
