### ISSUE TITLE
emailjs crashes when trying to operate with filtered SMTP commands

### ISSUE THREAD

**Issue by kzmkv** [eleith/emailjs#157]
Hi,

I have firewalled Microsoft Exchange server, when trying to send email using the following example i get crash due to the filtered SMTP commands. Firewalled server sends 250-AUTH which is the reason of this behaviour:

```
➤  cat test.js
var email   = require("emailjs");

var server  = email.server.connect({
   user:    "administrator",
   password:"password",
   host:    "w2012-1-idmu.w2012-idmu.corp",
   ssl:     false
});

server.smtp.debug(100);

server.send({
   text:    "i hope this works",
   from:    "you <username@your-email.com>",
   to:      "someone <user@me.com>",
   cc:      "else <else@your-email.com>",
   subject: "testing emailjs"
}, function(err, message) { console.log(err || message); });

➤  node test.js
connecting: w2012-1-idmu.w2012-idmu.corp
connected: w2012-1-idmu.w2012-idmu.corp:25
220 **************************************************************************************************

ehlo Alexs-MacBook-Pro.local

250-w2012-1-idmu.w2012-idmu.corp Hello [10.4.253.198]
250-SIZE 37748736
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-XXXXXXXA
250-XXXXXXXXXXXXXB
250-AUTH
250-XXXXXXXXXXXXXXXXXC
250-8BITMIME
250-BINARYMIME
250-XXXXXXXD
250 XXXXE

/private/tmp/mlr/node_modules/emailjs/smtp/smtp.js:456
            if ((self.features.auth || "").indexOf(preferred[i]) != -1) {
                                           ^

TypeError: (self.features.auth || "").indexOf is not a function
    at initiate (/private/tmp/mlr/node_modules/emailjs/smtp/smtp.js:456:44)
    at caller (/private/tmp/mlr/node_modules/emailjs/smtp/smtp.js:49:14)
    at attempt (/private/tmp/mlr/node_modules/emailjs/smtp/smtp.js:388:14)
    at caller (/private/tmp/mlr/node_modules/emailjs/smtp/smtp.js:49:14)
    at response (/private/tmp/mlr/node_modules/emailjs/smtp/smtp.js:318:13)
    at caller (/private/tmp/mlr/node_modules/emailjs/smtp/smtp.js:49:14)
    at response (/private/tmp/mlr/node_modules/emailjs/smtp/smtp.js:201:52)
    at caller (/private/tmp/mlr/node_modules/emailjs/smtp/smtp.js:49:14)
    at Socket.response (/private/tmp/mlr/node_modules/emailjs/smtp/smtp.js:182:11)
    at Socket.g (events.js:260:16)
```

**Comment by eleith** [comment]
can you try with master to see if this is still happening?

**Comment by eleith** [comment]
fixed in master
