### ISSUE TITLE
TypeError: Object true has no method 'indexOf'

### ISSUE THREAD

**Issue by luwenchaobh** [eleith/emailjs#166]
--> node test.js
connecting: ----------------
connected: ----------------
220 -----------------------------------------------------

ehlo vm-xx-xxx-xx-xx

250-xxxx.xxxx.xx Hello [xx.xxx.xx.xx]
250-SIZE 10485760
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-AUTH
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250-XEXCH50
250 XSHADOW

/root/test/node_modules/emailjs/smtp/smtp.js:483
           if (((self.features && self.features.auth) || "").indexOf(preferre
                                                             ^
TypeError: Object true has no method 'indexOf'
   at initiate (/root/test/node_modules/emailjs/smtp/smtp.js:483:63)
   at caller (/root/test/node_modules/emailjs/smtp/smtp.js:48:14)
   at attempt (/root/test/node_modules/emailjs/smtp/smtp.js:415:14)
   at caller (/root/test/node_modules/emailjs/smtp/smtp.js:48:14)
   at response (/root/test/node_modules/emailjs/smtp/smtp.js:345:13)
   at caller (/root/test/node_modules/emailjs/smtp/smtp.js:48:14)
   at response (/root/test/node_modules/emailjs/smtp/smtp.js:201:11)
   at caller (/root/test/node_modules/emailjs/smtp/smtp.js:48:14)
   at Socket.response (/root/test/node_modules/emailjs/smtp/smtp.js:181:11)
   at Socket.g (events.js:180:16)

**Comment by WirelessElephant** [comment]
Could you add some context to the issue? Printing a console debug provides limited description of the issue. What is going wrong? What are you trying to do? Can you provide code snippets?

**Comment by eleith** [comment]
not sure how self.features.auth gets set to true. i've added code to prevent that in the future.
