### ISSUE TITLE
smtp is undefined

### ISSUE THREAD

**Issue by MikePap** [eleith/emailjs#167]
I tried the module and I get this error:
`{ Error: connection encountered an error
    at module.exports (/.../../...../node_modules/emailjs/smtp/error.js:3:13)
    at TLSSocket.error (/..../..../node_modules/emailjs/smtp/response.js:26:29)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 5,
  previous: 
   Error: 139642356230016:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
          at Error (native),
  smtp: undefined }`

smtp is undefined ? 
It works if I try on 25: 
``
 telnet mail.kaipai.it 25 
``

**Comment by eleith** [comment]
can you provide the snippet that was used to get the error? i'm unable to reproduce otherwise.

**Comment by eleith** [comment]
smtp is undefined in the message that is passed back, but it is not an error that originally triggered the output.

this provides some clue: https://stackoverflow.com/questions/15421050/node-request-getting-error-ssl23-get-server-hellounknown-protocol

basically you might be using the wrong port when trying to connect. if you are using ssl it might be 587 or 465
