### ISSUE TITLE
Can't set headers after they are sent {'code':4}

### ISSUE THREAD

**Issue by franalt** [eleith/emailjs#168]
Hello everyone,

I'm getting an error with code 4. Turning debugging on I got this:

smtp connection destroyed!
Error: Can't set headers after they are sent.
at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
at ServerResponse.header (/app/node_modules/express/lib/response.js:718:10)
at ServerResponse.contentType (/app/node_modules/express/lib/response.js:551:15)
at ServerResponse.send (/app/node_modules/express/lib/response.js:138:14)
at Object.exports.renderFile (/app/node_modules/jade/lib/index.js:374:12)
at done (/app/node_modules/express/lib/response.js:957:10)
at View.exports.__express [as engine] (/app/node_modules/jade/lib/index.js:417:11)
at View.render (/app/node_modules/express/lib/view.js:126:8)
at tryRender (/app/node_modules/express/lib/application.js:639:10)
at EventEmitter.render (/app/node_modules/express/lib/application.js:591:3)

Does anyone know whats going on?

Any help is apreciated!

Thanks!

**Comment by sturad** [comment]
I saw similar error with a double callback.  Perhaps you could throw in break points before and after you call send() to verify.
   
I opened another issue https://github.com/eleith/emailjs/issues/174  Perhaps these are really duplicates if it is indeed the same root cause

**Comment by eleith** [comment]
@franalt  can you provide a snippet that reproduces this?

**Comment by eleith** [comment]
please see suggestions on #174 , perhaps the application upstream has made assumptions about when an error response is called, and then tries to handle every response (rather than only having one return and future ones stay dormant)

this is just a guess, but until i can get a snippet to isolate the problem, there is confusion as to where the bug occurs.
