### ISSUE TITLE
i have this friki error, help i gona explod

### ISSUE THREAD

**Issue by atlabiz** [eleith/emailjs#182]
## I have this error what I should  any help is gonna be welcome

```
{ Error: connection encountered an error
    at module.exports (/user_code/node_modules/emailjs/smtp/error.js:3:13)
    at TLSSocket.error (/user_code/node_modules/emailjs/smtp/response.js:26:29)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1020:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  code: 5,
  previous: 
   { Error: getaddrinfo ENOTFOUND mail.george.gr mail.george.gr:25
       at errnoException (dns.js:28:10)
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
     code: 'ENOTFOUND',
     errno: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'mail.george.gr',
     host: 'mail.george.gr',
     port: 25 },
  smtp: undefined }
```

## this is my index.js 

```
const email = require('./node_modules/emailjs/email');

const server 	= email.server.connect({
   user:    "support@george.gr", 
   password:"dtasadfransdsq12!", 
   host:    "smtp.george.gr", 
   ssl:     true,
   port: 25
});


exports.sendContactMessage = functions.database.ref('/emails/{pushKey}').onWrite(event => {
  
  const snapshot = event.data;
  
  // Only send email for new messages.
  if (snapshot.previous.val() || !snapshot.val().name) {
    return;
  }
  
  const val = snapshot.val();

  console.log(val);

  // send the message and get a callback with an error or details of the message that was sent
  server.send({
    text:    "i hope this works", 
    from:    "george@gmail.com", 
    to:      "support@george.gr",
    cc:      "support@george.gr",
    subject: "testing emailjs"
  }, function(err, message) { console.log(err || message); });



});


```

**Comment by rakhi2104** [comment]
I'm too facing the same error calling the Cloud Function on Firebase 😕

**Comment by eleith** [comment]
the error is thrown because the local machine you are on can not contact `mail.george.gr` for some reason.

are you behind a vpn or have some host rules that would prevent the network from being able to make contact to the host you are trying to talk to?

can you get other domains to work?

it doesn't seem like it is an issue directly with this project but might be something more local to the machines you are testing on. i'll give this a go on cloud function to see if there is some network blocking going on.

**Comment by nrickles3** [comment]
Is there a way to set up proxy settings within emailjs? I have my proxy settings set up with npm, but I still get the error described above.
