### ISSUE TITLE
SMTP connection destroyed! (error code 5)

### ISSUE THREAD

**Issue by nrickles3** [eleith/emailjs#189]
I am attempting to send emails through my gmail account. Here is my code:
```
var email = require('emailjs');
var server = email.server.connect({
    user: "emailaddress@gmail.com",
    password: "password",
    host: "smtp.gmail.com",
    port: 465,
    ssl: true
  });

  server.send({
    text: "asdf",
    from: "emailaddress@gmail.com",
    to:   "otheremailaddress@gmail.com",
    subject: "test"
  }, function(err, message) {
    console.log(err || message);
  });
```
And I receive this error:
```
connecting: smtp.gmail.com:465
smtp connection destroyed!
{ Error: connection encountered an error (getaddrinfo ENOTFOUND smtp.gmail.com smtp.gmail.com:465)
    at module.exports (C:\Users\...\emailjs\smtp\error.js:2:13)
    at TLSSocket.error (C:\Users\...\emailjs\smtp\response.js:26:29)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 5,
  previous:
   { Error: getaddrinfo ENOTFOUND smtp.gmail.com smtp.gmail.com:465
       at errnoException (dns.js:28:10)
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
     code: 'ENOTFOUND',
     errno: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'smtp.gmail.com',
     host: 'smtp.gmail.com',
     port: 465 },
  smtp: undefined }
```
I have read that others have had the same issue and that maybe a proxy was to blame. I am behind a proxy, so is there any way to get through it? I have my proxy settings configured with npm (I can successfully make npm install calls), so is there something more I need to do to get this working with emailjs?

**Comment by eleith** [comment]
it certainly looks like the proxy is tripping up the library.

i don't have experience with this directly, a quick google search turns up some advice on what to do. here is one blog i found: https://www.vanamco.com/2014/06/24/proxy-requests-in-node-js/
