### ISSUE TITLE
Not working with email servers that do not require authentication

### ISSUE THREAD

**Issue by kwisatz** [eleith/emailjs#210]
I realize there's been another ticket about this that has been closed, but I'm afraid I have the exact same symptoms and we're unable to make this work.

When trying to send mail through our internal relay true a trusted network that doesn't require authentication, emailjs fails to send the mail with `"err":{"message":"no form of authorization supported", code":7}`

I have provided as much anonymized detail as possible:

```
connecting: mx.internal.tld:25
connected: mx.internal.tld:25
220 TheCompany Mail

ehlo scarif

250-mail.thecompany.tld
250-PIPELINING
250-SIZE 1024000000
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 DSN

starttls

220 2.0.0 Ready to start TLS

ehlo scarif

250-mail.thecompany.tld
250-PIPELINING
250-SIZE 1024000000
250-ETRN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 DSN

{"name":"project-dev","hostname":"scarif","pid":844,"level":50,"msg":"Code 500 error:","time":"2017-12-13T10:20:57.306Z","v":0}
{"name":"project-dev","hostname":"scarif","pid":844,"level":50,"err":{"message":"no form of authorization supported","name":"Error","stack":"Error: no form of authorization supported\n    at module.exports (/var/www/project/releases/20171212135830/node_modules/project-server/node_modules/emailjs/smtp/error.js:2:13)\n    at initiate (/var/www/project/releases/20171212135830/node_modules/project-server/node_modules/emailjs/smtp/smtp.js:543:44)\n    at caller (/var/www/project/releases/20171212135830/node_modules/project-server/node_modules/emailjs/smtp/smtp.js:48:14)\n    at attempt (/var/www/project/releases/20171212135830/node_modules/project-server/node_modules/emailjs/smtp/smtp.js:415:14)\n    at caller (/var/www/project/releases/20171212135830/node_modules/project-server/node_modules/emailjs/smtp/smtp.js:48:14)\n    at response (/var/www/project/releases/20171212135830/node_modules/project-server/node_modules/emailjs/smtp/smtp.js:345:13)\n    at caller (/var/www/project/releases/20171212135830/node_modules/project-server/node_modules/emailjs/smtp/smtp.js:48:14)\n    at response (/var/www/project/releases/20171212135830/node_modules/project-server/node_modules/emailjs/smtp/smtp.js:201:11)\n    at caller (/var/www/project/releases/20171212135830/node_modules/project-server/node_modules/emailjs/smtp/smtp.js:48:14)\n    at TLSSocket.response (/var/www/project/releases/20171212135830/node_modules/project-server/node_modules/emailjs/smtp/smtp.js:181:11)\n    at Object.onceWrapper (events.js:318:30)\n    at emitTwo (events.js:125:13)\n    at TLSSocket.emit (events.js:213:7)\n    at notify (/var/www/project/releases/20171212135830/node_modules/project-server/node_modules/emailjs/smtp/response.js:19:14)\n    at TLSSocket.watch (/var/www/project/releases/20171212135830/node_modules/project-server/node_modules/emailjs/smtp/response.js:44:7)\n    at emitOne (events.js:115:13)","code":7},"msg":"no form of authorization supported","time":"2017-12-13T10:20:57.307Z","v":0}
quit

221 2.0.0 Bye

smtp connection closed.
```

I can confirm that sending mail works if I connect to the mail server through the public interface (which requires authentication)

In that case, the smtp headers contain an `AUTH` header, which is missing from the previous conversation:

```
ehlo scarif

250-mail.thecompany.tld
250-PIPELINING
250-SIZE 1024000000
250-ETRN
250-AUTH PLAIN
250-AUTH=PLAIN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 DSN
```

**Comment by eleith** [comment]
if you comment out this line: https://github.com/eleith/emailjs/blob/master/smtp/smtp.js#L543

does it work?

**Comment by zackschuster** [comment]
closing due to unresponsiveness.

@kwisatz please re-open if you're still having this issue & would like to move forward :)
