### ISSUE TITLE
No form of authorization supported

### ISSUE THREAD

**Issue by naveenkumar87** [eleith/emailjs#212]
I am using these configurations : 
```
var emailConfig = {
			   user:    'useremail',
			   password:'pass' 
			   host:    HOST, 
			   port: 	25,
			   ssl:     false,
			   authentication: ['PLAIN', 'LOGIN']
		};
```
Error -

```
{ Error: no form of authorization supported
    at module.exports (node_modules\emailjs\smtp\error.js:2:13)
    at initiate (node_modules\emailjs\smtp\smtp.js:553:44)
    at caller (node_modules\emailjs\smtp\smtp.js:48:14)
    at attempt (node_modules\emailjs\smtp\smtp.js:415:14)
    at caller (node_modules\emailjs\smtp\smtp.js:48:14)
    at response (node_modules\emailjs\smtp\smtp.js:345:13)
    at caller (node_modules\emailjs\smtp\smtp.js:48:14)
    at response (node_modules\emailjs\smtp\smtp.js:201:11)
    at caller (node_modules\emailjs\smtp\smtp.js:48:14)
    at Socket.response (node_modules\emailjs\smtp\smtp.js:181:11)
  code: 7,
  smtp: '250-HOST Hello [10.72.66.60]\n250-SIZE\r\n250-PIPELINING\r\n250-DSN\r\n250-ENHANCEDSTATUSCODES\r\n250-STARTTLS\r\n250-AUTH\r\n250-8BITMIME\r\n250-BINARYMIME\r\n250 CHUNKING
\r\n' }
```

in smtp.js method is going as undefined, after setting the method to 'PLAIN' or 'LOGIN' i am getting different error : 

```
{ Error: authorization.failed (bad response on command 'AUTH': 5.7.4 Unrecognized authentication type)
    at module.exports (node_modules\emailjs\smtp\error.js:2:13)
    at failed (node_modules\emailjs\smtp\smtp.js:501:28)
    at response (node_modules\emailjs\smtp\smtp.js:506:13)
    at caller (node_modules\emailjs\smtp\smtp.js:48:14)
    at response (node_modules\emailjs\smtp\smtp.js:207:11)
    at caller (node_modules\emailjs\smtp\smtp.js:48:14)
    at Socket.response (node_modules\emailjs\smtp\smtp.js:181:11)
    at Socket.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
  code: 3,
  previous:
   { Error: bad response on command 'AUTH': 5.7.4 Unrecognized authentication type
       at module.exports (node_modules\emailjs\smtp\error.js:2:13)
       at response (node_modules\emailjs\smtp\smtp.js:207:28)
       at caller (node_modules\emailjs\smtp\smtp.js:48:14)
       at Socket.response (node_modules\emailjs\smtp\smtp.js:181:11)
       at Socket.g (events.js:292:16)
       at emitTwo (events.js:106:13)
       at Socket.emit (events.js:191:7)
       at notify (node_modules\emailjs\smtp\response.js:19:14)
       at Socket.watch (node_modules\emailjs\smtp\response.js:44:7)
       at emitOne (events.js:96:13)
     code: 2,
     smtp: '504 5.7.4 Unrecognized authentication type\n' },
  smtp: undefined }
Error sending email for user invite :
{ Error: authorization.failed (bad response on command 'AUTH': 5.7.4 Unrecognized authentication type)
    at module.exports (node_modules\emailjs\smtp\error.js:2:13)
    at failed (node_modules\emailjs\smtp\smtp.js:501:28)
    at response (node_modules\emailjs\smtp\smtp.js:506:13)
    at caller (node_modules\emailjs\smtp\smtp.js:48:14)
    at response (node_modules\emailjs\smtp\smtp.js:207:11)
    at caller (node_modules\emailjs\smtp\smtp.js:48:14)
    at Socket.response (node_modules\emailjs\smtp\smtp.js:181:11)
    at Socket.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
  code: 3,
  previous:
   { Error: bad response on command 'AUTH': 5.7.4 Unrecognized authentication type
       at module.exports (node_modules\emailjs\smtp\error.js:2:13)
       at response (node_modules\emailjs\smtp\smtp.js:207:28)
       at caller (node_modules\emailjs\smtp\smtp.js:48:14)
       at Socket.response (node_modules\emailjs\smtp\smtp.js:181:11)
       at Socket.g (events.js:292:16)
       at emitTwo (events.js:106:13)
       at Socket.emit (events.js:191:7)
       at notify (node_modules\emailjs\smtp\response.js:19:14)
       at Socket.watch (node_modules\emailjs\smtp\response.js:44:7)
       at emitOne (events.js:96:13)
     code: 2,
     smtp: '504 5.7.4 Unrecognized authentication type\n' },
  smtp: undefined }
```

Auths supported by the SMTP server -

```
250-HOST Hello [10.72.66.60]
250-SIZE
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-AUTH
250-8BITMIME
250-BINARYMIME
250 CHUNKING
```

**Comment by eleith** [comment]
i believe your smtp server needs SSL to be true in the config. have you tried that?

**Comment by hemant-manwani** [comment]
```
  user: 'username@gmail.com',
  password: 'password',
  host: 'smtp.gmail.com',
  port: '587',
  tls: true,
```
is working
