### ISSUE TITLE
SMTPError: no connection has been established

### ISSUE THREAD

**Issue by developeron29** [eleith/emailjs#253]
When trying to connect to my SMTP server using these configuration: 

I've removed personal private auth details below
```
import { SMTPClient } from 'emailjs';

const client = new SMTPClient({
	user: '<user>@<domain>.com',
	password: '<pass>',
  host: '<smtp-server>',
  port: 587,
  tls:true
});

// send the message and get a callback with an error or details of the message that was sent
client.send(
	{
		text: 'i hope this works',
		from: '<email here>',
		to: '<sender here>',
		subject: 'testing emailjs',
	},
	(err, message) => {
		console.log(err || message);
	}
);
```

getting this error

SMTPError: no connection has been established
    at Function.create (file:///Users/ayushnarula/Desktop/nodemail/node_modules/emailjs/rollup/email.mjs:15122:21)
    at SMTPConnection.send (file:///Users/ayushnarula/Desktop/nodemail/node_modules/emailjs/rollup/email.mjs:15431:40)
    at SMTPConnection.command (file:///Users/ayushnarula/Desktop/nodemail/node_modules/emailjs/rollup/email.mjs:15462:14)
    at SMTPConnection.helo (file:///Users/ayushnarula/Desktop/nodemail/node_modules/emailjs/rollup/email.mjs:15479:14)
    at file:///Users/ayushnarula/Desktop/nodemail/node_modules/emailjs/rollup/email.mjs:15683:26
    at caller (file:///Users/ayushnarula/Desktop/nodemail/node_modules/emailjs/rollup/email.mjs:15236:9)
    at file:///Users/ayushnarula/Desktop/nodemail/node_modules/emailjs/rollup/email.mjs:15554:17
    at caller (file:///Users/ayushnarula/Desktop/nodemail/node_modules/emailjs/rollup/email.mjs:15236:9)
    at response (file:///Users/ayushnarula/Desktop/nodemail/node_modules/emailjs/rollup/email.mjs:15449:17)
    at caller (file:///Users/ayushnarula/Desktop/nodemail/node_modules/emailjs/rollup/email.mjs:15236:9) {
  code: 6,
  smtp: undefined,
  previous: null
}

**Comment by zackschuster** [comment]
does this only happen for `tls: true`? does changing the port do anything?

would you be able to turn on debug mode (call `client.smtp.debug(1)` before sending) and share the logs?

**Comment by developeron29** [comment]
Thanks @zackschuster, Removing tls:true and keeping the port to 587 let me successfully send emails using emailjs and my smtp.

Thanks for the help!
Closing.
