### ISSUE TITLE
Error [ERR_REQUIRE_ESM] - Remix

### ISSUE THREAD

**Issue by alessrdrgz** [eleith/emailjs#320]
I'm trying to use this library with Remix and when I'm trying to run it it shows this error: 
`Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\emailjs\email.js from C:\Users\alessandro.rodriguez\blueflick-remix\build\index.js not supported.
Instead change the require of email.js in C:\Users\alessandro.rodriguez\blueflick-remix\build\index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\Users\alessandro.rodriguez\blueflick-remix\build\index.js:725:22)
    at C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\@remix-run\serve\index.js:43:17
    at Layer.handle [as handle_request] (C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\express\lib\router\route.js:137:13)
    at next (C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\express\lib\router\route.js:131:14)
    at next (C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\express\lib\router\route.js:131:14)
    at next (C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\express\lib\router\route.js:131:14)
    at next (C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\express\lib\router\route.js:131:14)
    at next (C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\express\lib\router\route.js:131:14)
    at next (C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\express\lib\router\route.js:131:14)
    at Route.dispatch (C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\express\lib\router\index.js:281:22
    at param (C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\express\lib\router\index.js:360:14)
    at param (C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\express\lib\router\index.js:371:14)
    at Function.process_params (C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\express\lib\router\index.js:416:3)
    at next (C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\express\lib\router\index.js:275:10)
    at logger (C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\express\lib\router\index.js:323:13)
    at C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\express\lib\router\index.js:341:12)
    at next (C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\express\lib\router\index.js:275:10)
    at SendStream.error (C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\serve-static\index.js:121:7)
    at SendStream.emit (node:events:526:28)
    at SendStream.error (C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\send\index.js:270:17)
    at SendStream.onStatError (C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\send\index.js:421:12)
    at next (C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\send\index.js:735:16)
    at onstat (C:\Users\alessandro.rodriguez\blueflick-remix\node_modules\send\index.js:724:14)
    at FSReqCallback.oncomplete (node:fs:198:21)`

And I'm importing the library like this:
`import { SMTPClient } from "emailjs";`

I'm doing something wrong?

**Comment by zackschuster** [comment]
it seems like your code is being compiled to commonjs, presumably by babel or typescript. what does your build step look like?

**Comment by diegocontreras2** [comment]
**I have the same error**

```
internal/modules/cjs/loader.js:1080
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\analista4\Documents\VisualStudioCodeProjects\Vue\labquimico_backend\node_modules\emailjs\email.js
require() of ES modules is not supported.
require() of C:\Users\analista4\Documents\VisualStudioCodeProjects\Vue\labquimico_backend\node_modules\emailjs\email.js from C:\Users\analista4\Documents\VisualStudioCodeProjects\Vue\labquimico_backend\utils\Email.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename email.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\analista4\Documents\VisualStudioCodeProjects\Vue\labquimico_backend\node_modules\emailjs\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\analista4\Documents\VisualStudioCodeProjects\Vue\labquimico_backend\utils\Email.js:1:24)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Email.js**

```
const { SMTPClient } = require('emailjs');

const client = new SMTPClient({
	user: 'myuser@outlook.com',
	password: 'mypassword',
	host: 'smtp-mail.outlook.com',
	ssl: true,
});

module.exports = client
```

**it was working with the version:**
` "emailjs": "^3.8.0"`

**After I updated the last version and I get the previous error**

`"emailjs": "^4.0.0"`

**package.json**

```
{
  "name": "labquimico-backend",
  "version": "1.1.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node ./app.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "cors": "^2.8.5",
    "emailjs": "^4.0.0",
    "express": "^4.17.3",
    "ip": "^1.1.5",
    "pg": "^8.7.3"
  }
}
```

**Comment by zackschuster** [comment]
@diegocontreras2 we removed support for commonjs in v4. please see https://github.com/eleith/emailjs/discussions/317#discussioncomment-2793650 for more.

**Comment by diegocontreras2** [comment]
Unfortunately I can't change all the files to use import, and because of the update I did it doesn't let me run the express server anymore, I'll have to migrate to another module, thanks.

**Comment by delventhalz** [comment]
Fwiw, I spent a number of hours debugging this issue today. It would have helped a lot to have a note in the Readme explaining that only es modules are supported and to install 3.8.1 if you need commonjs.
